name: Deploy to PROD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1) Create a unique release name using date/time
      - name: Set release name
        run: |
          echo "RELEASE_NAME=prod-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
          echo "Release name: $RELEASE_NAME"

      # 2) Create the release directory on the TEST server
      - name: Create release directory on TEST
        run: |
          ssh -o StrictHostKeyChecking=no root@192.168.1.29 \
            "mkdir -p /var/www/mini-prod/releases/$RELEASE_NAME"

      # 3) Copy ONLY app files to that release
      - name: Copy app files to new release
        run: |
          cd "$GITHUB_WORKSPACE"
          rsync -avz \
            index.php \
            version.txt \
            root@192.168.1.29:/var/www/mini-prod/releases/$RELEASE_NAME/

      # 4) Switch 'current' symlink to point to the new release + reload nginx
      - name: Switch current symlink and reload nginx
        run: |
          ssh -o StrictHostKeyChecking=no root@192.168.1.29 \
            "ln -sfn /var/www/mini-prod/releases/$RELEASE_NAME /var/www/mini-prod/current && systemctl reload nginx"

      
      - name: Cleanup old releases
        run: |
          ssh -o StrictHostKeyChecking=no root@192.168.1.29 \
            "cd /var/www/mini-prod/releases && ls -1t | tail -n +6 | xargs -r rm -rf"
    

